---
# tasks file for apache
 
  - include_vars: "{{ ansible_os_family }}.yml"
 
  - import_tasks: install.yml
 
  - import_tasks: service.yml
 
  - import_tasks: config.yml
    when: ansible_os_family == 'RedHat'
  