---
# tasks file for frontend
- include_vars: "{{ ansible_os_family }}.yml"
- name: create app directory
  file:
    path: /opt/app
    owner: "{{ apache.user }}"
    group: "{{ apache.group }}"
    mode: 0755
    state: directory

- name: create release path
  file:
    path: /opt/app/release
    owner: "{{ apache.user }}"
    group: "{{ apache.group }}"
    mode: 0755
    state: directory


- name: Download and extract the release
  unarchive:
    src: https://github.com/devopsdemoapps/devops-demo-app/archive/{{ app.version }}.tar.gz
    dest: /opt/app/release
    owner: "{{ apache.user }}"
    group: "{{ apache.group }}"
    creates: /opt/app/release/devops-demo-app-{{ app.version }}
    remote_src: yes

- name: create a symlink
  file:
    src: /opt/app/release/devops-demo-app-{{ app.version }}
    dest: /var/www/html/app
    owner: "{{ apache.user }}"
    group: "{{ apache.group }}"
    state: link

- name: add application configs
  template:
    src: config.ini.j2
    dest: /var/www/html/app/config.ini
    owner: "{{ apache.user }}"
    group: "{{ apache.group }}"
    mode: 0644
