---
# tasks file for php
  - name: install php
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - php
      - php-mysql
      - nmap
    notify: Restart apache service

  - name: additional php packages on debian 
    package: 
      name: "{{ item }}"
      state: present 
    with_items: 
      - libapache2-mod-php
    when: ansible_os_family == 'Debian'
    notify: restart apache2 for debian
    
